dist:     focal
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - lcov
      - gcovr

install:
  - sudo apt-get install valgrind
  - sudo pip3 install cpplint
  - sudo apt install cppcheck
  - sudo apt install libgtest-dev

before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt && sudo make
  - cd "${TRAVIS_BUILD_DIR}"/
  - sudo mkdir build && cd build
  - sudo cmake ..
  - sudo make
  - cd ..
  - cd ..

script:
  - cpplint --extensions=c,cpp HW_2/project/src/* HW_2/project/include/* HW_2/tests/*
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./
  - valgrind --track-origins=yes --child-silent-after-fork=yes --leak-check=full "${TRAVIS_BUILD_DIR}"/build/TEST
