dist:     focal
sudo:     required

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - lcov
      - gcovr

install:
  - sudo apt-get install valgrind
  - sudo pip3 install cpplint
  - sudo apt install cppcheck

before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt && sudo make
  - cd "${TRAVIS_BUILD_DIR}"/HW_2/tests
  - bash generate_tests.sh
  - cd ..
  - mkdir build && cd build
  - cmake ..
  - make clean && make
  - cd ..
  - cd ..

script:
  - cpplint --extensions=c,cpp HW_2/project/include/one/* HW_2/project/include/multi/* HW_2/project/src/one/* HW_2/project/src/multi/* HW_2/tests/*.cpp
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./HW_2/project
  - ./HW_2/build/TEST
  - valgrind --track-origins=yes --child-silent-after-fork=yes --leak-check=full ./HW_2/build/TEST_VALGRIND
  - cd HW_2/
  - cd build/
  - ./TEST_MAIN
  - cd "${TRAVIS_BUILD_DIR}"/HW_2/project
  - bash <(curl -s https://codecov.io/bash)
